# .github/workflows/basic.yml
name: Basic Workflow

on: push

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16
      - run: xcode-select --print-path
      - run: python find_sdk.py 15 --print_sdk_path
